import math

#  Basic game settings
RES = WIDTH, HEIGHT = 1700, 1900
HALF_WITH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

PLAYER_POS = 1.5, 5  #For mini map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

#  Ray casting settings
FOV = math.pi / 2
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

# Projecting map
SCREEN_DIST = HALF_WITH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

